export default [
    {
        native: true,
        protocolToken: false,
        name: "UBC",
        symbol: "UBC",
        decimals: 18,
        protocolSeizeShare: 0.5,
        reserveFactor: 0.2,
        collateralFactor: 0.7,
        price: 20.5,
        faucetTokenAddress: "",
        CTokenAddress: ""
    },
    {
        native: false,
        protocolToken: true,
        name: "COMP",
        symbol: "COMP",
        decimals: 18,
        protocolSeizeShare: 0.5,
        reserveFactor: 0.3,
        collateralFactor: 0.6,
        price: 2.54,
        faucetTokenAddress: "",
        CTokenAddress: ""
    },
    {
        native: false,
        protocolToken: false,
        name: "USD Coin",
        symbol: "USDC",
        decimals: 6,
        protocolSeizeShare: 0.5,
        reserveFactor: 0.3,
        collateralFactor: 0.8,
        price: 1,
        faucetTokenAddress: "",
        CTokenAddress: ""
    },
    {
        native: false,
        protocolToken: false,
        name: "Tether",
        symbol: "USDT",
        decimals: 6,
        protocolSeizeShare: 0.5,
        reserveFactor: 0.3,
        collateralFactor: 0.7,
        price: 1,
        faucetTokenAddress: "",
        CTokenAddress: ""
    },
    {
        native: false,
        protocolToken: false,
        name: "Ethereum",
        symbol: "ETH",
        decimals: 18,
        protocolSeizeShare: 0.5,
        reserveFactor: 0.3,
        collateralFactor: 0.75,
        price: 1965.42,
        faucetTokenAddress: "",
        CTokenAddress: ""
    },
    {
        native: false,
        protocolToken: false,
        name: "Bitcoin",
        symbol: "BTC",
        decimals: 8,
        protocolSeizeShare: 0.5,
        reserveFactor: 0.3,
        collateralFactor: 0.6,
        price: 18952.21,
        faucetTokenAddress: "",
        CTokenAddress: ""
    },
];